services:
  twig:
    class: "\\Twig_Environment"
    arguments:
        loader: "@twig.loader"
  view.factory:
    class: "\\LoT\\Application\\View\\Factory"
    arguments:
        twig: "@twig"
  controller.index:
    class: "\\LoT\\Controller\\IndexController"
    arguments:
        viewFactory: "@view.factory"